export default [
  {
    id: 1,
    img: {
      src: "https://scrimba.com/links/travel-journal-japan-image-url",
      alt: "Mount Fuji",
    },
    title: "Mount Fuji",
    country: "Japan",
    googleMapsLink: "https://maps.app.goo.gl/6RLYZDuuuqJ7kNGZ9",
    dates: "12 Jan, 2021 - 24 Jan, 2021",
    text: "Mount Fuji is the tallest mountain in Japan, standing at 3,776 meters (12,380 feet). Mount Fuji is the single most popular tourist site in Japan, for both Japanese and foreign tourists.",
  },
  {
    id: 2,
    img: {
      src: "https://scrimba.com/links/travel-journal-australia-image-url",
      alt: "Sydney Opera House",
    },
    title: "Sydney Opera House",
    country: "Australia",
    googleMapsLink: "https://maps.app.goo.gl/Zr17SCrsJeCEKMd36",
    dates: "27 May, 2021 - 8 Jun, 2021",
    text: "The Sydney Opera House is a multi-venue performing arts centre in Sydney. Located on the banks of the Sydney Harbour, it is often regarded as one of the 20th century's most famous and distinctive buildings.",
  },
  {
    id: 3,
    img: {
      src: "https://scrimba.com/links/travel-journal-norway-image-url",
      alt: "Geirangerfjord",
    },
    title: "Geirangerfjord",
    country: "Norway",
    googleMapsLink: "https://maps.app.goo.gl/fhkJuBhmFDv47tiB7",
    dates: "01 Oct, 2021 - 18 Nov, 2021",
    text: "The Geiranger Fjord is a fjord in the Sunnmøre region of Møre og Romsdal county, Norway. It is located entirely in the Stranda Municipality.",
  },
  {
    id: 4,
    img: {
      src: "https://images.pexels.com/photos/1454409/pexels-photo-1454409.jpeg",
      alt: "Hunza Valley in Autumn",
    },
    title: "Hunza Valley",
    country: "Pakistan",
    googleMapsLink: "https://goo.gl/maps/z2x4Wz3qR4R2",
    dates: "15 Apr, 2022 - 25 Apr, 2022",
    text: "Hunza is a mountainous valley in the Gilgit-Baltistan region. Famous for its spectacular scenery, vibrant culture, and the ancient Baltit and Altit Forts, it is often referred to as heaven on earth.",
  },
  {
    id: 5,
    img: {
      src: "https://images.pexels.com/photos/29543395/pexels-photo-29543395.png",
      alt: "Turquoise waters of Attabad Lake",
    },
    title: "Attabad Lake",
    country: "Pakistan",
    googleMapsLink: "https://goo.gl/maps/a1b2C3d4E5F6",
    dates: "26 Apr, 2022 - 28 Apr, 2022",
    text: "Attabad Lake is a mesmerizing turquoise lake in the Gojal Valley of Hunza. It was created naturally in 2010 following a massive landslide and has since become a major hub for boating and jet skiing.",
  },
  {
    id: 6,
    img: {
      src: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Nanga_Parbat_The_Killer_Mountain.jpg/960px-Nanga_Parbat_The_Killer_Mountain.jpg",
      alt: "Fairy Meadows with Nanga Parbat in the background",
    },
    title: "Fairy Meadows",
    country: "Pakistan",
    googleMapsLink: "https://goo.gl/maps/x7y8Z9w0V1U2",
    dates: "02 May, 2022 - 08 May, 2022",
    text: "Fairy Meadows is a lush green alpine pasture situated at the base of Nanga Parbat, the ninth-highest mountain in the world. It is heavily forested with alpine pines and offers up-close views of the towering peak.",
  },
  {
    id: 7,
    img: {
      src: "https://images.pexels.com/photos/33784883/pexels-photo-33784883.jpeg",
      alt: "Skardu Valley cold desert",
    },
    title: "Skardu Valley",
    country: "Pakistan",
    googleMapsLink: "https://goo.gl/maps/m3n4P5q6R7S8",
    dates: "10 May, 2022 - 20 May, 2022",
    text: "Skardu is the ultimate gateway to the Karakoram mountain range and the famous K2 base camp. The valley is known for its stark beauty, high-altitude cold deserts, and massive glaciers like Baltoro.",
  },
  {
    id: 8,
    img: {
      src: "https://images.pexels.com/photos/14106338/pexels-photo-14106338.jpeg",
      alt: "Deosai National Park plains",
    },
    title: "Deosai National Park",
    country: "Pakistan",
    googleMapsLink: "https://goo.gl/maps/bHj7X6m5R1A2",
    dates: "22 May, 2022 - 25 May, 2022",
    text: "Deosai National Park is the second-highest alpine plain in the world. Often called the 'Land of Giants', it is renowned for its sprawling wild flora and as a protected habitat for the rare Himalayan brown bear.",
  },
  {
    id: 9,
    img: {
      src: "https://images.pexels.com/photos/5809247/pexels-photo-5809247.jpeg",
      alt: "Khunjerab Pass border",
    },
    title: "Khunjerab Pass",
    country: "Pakistan",
    googleMapsLink: "https://goo.gl/maps/aL9bX8m4V2C1",
    dates: "30 May, 2022 - 01 Jun, 2022",
    text: "The Khunjerab Pass is the highest paved international border crossing in the world, connecting Pakistan and China through the majestic Karakoram mountains at an elevation of 4,693 meters.",
  },
  {
    id: 10,
    img: {
      src: "https://images.pexels.com/photos/20522853/pexels-photo-20522853.jpeg",
      alt: "Naltar Valley lakes",
    },
    title: "Naltar Valley",
    country: "Pakistan",
    googleMapsLink: "https://goo.gl/maps/cVk9H8n7M4B3",
    dates: "05 Jun, 2022 - 10 Jun, 2022",
    text: "Renowned for its vibrant, colorful alpine lakes and dense pine forests, Naltar Valley is a hidden gem. The dramatic color of its lakes comes from the rich minerals in the water, making it a must-see.",
  },
  {
    id: 11,
    img: {
      src: "https://images.unsplash.com/photo-1589553416260-f586c8f1514f?q=80&w=1000&auto=format&fit=crop",
      alt: "Phander Valley lake",
    },
    title: "Phander Valley",
    country: "Pakistan",
    googleMapsLink: "https://goo.gl/maps/dWk4L7p8N5C4",
    dates: "12 Jun, 2022 - 16 Jun, 2022",
    text: "Often called 'Little Kashmir', Phander Valley in the Ghizer District is famous for its mesmerizing deep blue lake, lush green fields, and peaceful trout-filled river. It's one of the most serene locations in the region.",
  },
];
